save_path: 
# condition_file: './dataset/maestro-v3.0.0/2004/MIDI-Unprocessed_SMF_02_R1_2004_01-05_ORIG_MID--AUDIO_02_R1_2004_05_Track05_wav.midi'
condition_file: './debug/sample_data.midi'
length: 2048
threshold_len: 500
checkpoint_pth: 'train-1098.pth'